In [135]:
                                    #section-A:-Datastructures and control structures

In [133]:
# Data structures set A
# list it is mutable it can be modify  
D=[1,2,3,4,5]
D

[1, 2, 3, 4, 5]

In [3]:
D.append(6)     #adding the values
D

[1, 2, 3, 4, 5, 6]

In [4]:
D1=[7,8,9,10]
D1

[7, 8, 9, 10]

In [5]:
D.extend(D1)
D

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
D.insert(2,11)
D

[1, 2, 11, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
D.remove(11)
D

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
D.pop()
D

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
len(D)



9

In [16]:
D.sort()
D

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
D.reverse()
D

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [18]:
D.clear()
D

[]

In [27]:
# 2) tuple
# Creating a tuple with 3 student names
students = ("hema", "sweety", "shiva")

# Trying to change the second name
students[1] = "Anjali"
 # it can not be change or modify because it is immutable

TypeError: 'tuple' object does not support item assignment

In [32]:
# 2) set
S1=[1,2,4,4,5,5,8,9,6,7,10,12,11]
S2=set(S1)  #it will remove duplicates and it will arrange in order
S2

{1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12}

In [42]:
# 4) dictinory it contains keys and values   
f1={"name":'hema',"age":22,"city":'hyd'}   
f1

{'name': 'hema', 'age': 22, 'city': 'hyd'}

In [43]:
f1["email"]="hema@"  # added the new key email 
f1

{'name': 'hema', 'age': 22, 'city': 'hyd', 'email': 'hema@'}

In [9]:
#5) if statement 
age=24    
if age>=18:
    print(" you are eligible to vote")

 you are eligible to vote


In [29]:
#6) if-else-statement
# Example marks variable
marks = 75
if marks >= 90 and marks<=90:
    print("Grade: A")
elif marks >= 75 and marks<=89:  # 75 to 89
    print("Grade: B")
elif marks >= 50 :  # 50 to 74
    print("Grade: C")
else:  # below 50
    print("Fail")

                  
                      
            
                  

Grade: B


In [70]:
# 7) Input number
num = 19
if num > 0:
    if num % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but not even.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


The number is positive but not even.


In [71]:
                                         # section -B (Numpy)

In [73]:
# 8) numpy 
import numpy as np
N=np.array(5)
print("scalar:",N)
N1=np.array([1,2,3,4,5])
print("1D array:",N1) 
N2=np.array([[10,20,30],[40,50,60]])
print("2D array:\n",N2)     #2D array 

scalar: 5
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


In [74]:
#9) random numbers 0-100
R=np.random.randint(0,100,size=(4,4))
R

array([[37, 57, 21, 84],
       [30, 50,  2, 17],
       [42, 80, 14, 85],
       [89, 33, 42, 66]], dtype=int32)

In [96]:
#10) convert into DataFrame
D=np.array([[10,20,30],[40,50,60],[70,80,90]])  # created a 2D numpy array of shape (3x3)
print(D)
import pandas as pd
S=pd.DataFrame(data)  # converted into pandas DataFrame
print(S)
S.columns=["A","B","C"]  # added names into columns names
print(S)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90
    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


In [ ]:
                                     section-c:-exploring pandas

In [132]:
#11) exploring data
import pandas as pd
import numpy as np
data={"Name": ['hema','shivaram','sravani','harsha','swathi','sowmya','maha','killer','sweety','jannu'],
     "Age":[22,43,67,89,23,24,23,21,18,19],
      "City": ['NY', 'LA', 'SF', 'NY', 'LA', 'SF', 'NY', 'LA', 'SF', 'NY'],
      "Salary": [50000, 60000, 55000, np.nan, 58000, 62000, 57000, 61000, 59000, 6000]} # 1. Create a DataFrame manually
df=pd.DataFrame(data)  
print(df)    # 2. Display DataFrame info and statistics
df.info()   
df.describe()
print(df[["Name","City"]]) # 3. Select 'Name' and 'City' columns
df1 = df.drop('City', axis=1)
print("\nDataFrame without City column:") # 4. Drop 'City' column
print(df1)
df2=np.round(df["Salary"].mean(),1)
df2
df['Salary'].fillna(value=df2, inplace=True)
print("\nDataFrame after filling missing Salary values:") # 5. Fill missing values in 'Salary' with mean
print(df)
df3 = df.drop_duplicates()
print("\nDataFrame after removing duplicates:")  # 6. Remove duplicate rows (if any)
print(df3)



       Name  Age City   Salary
0      hema   22   NY  50000.0
1  shivaram   43   LA  60000.0
2   sravani   67   SF  55000.0
3    harsha   89   NY      NaN
4    swathi   23   LA  58000.0
5    sowmya   24   SF  62000.0
6      maha   23   NY  57000.0
7    killer   21   LA  61000.0
8    sweety   18   SF  59000.0
9     jannu   19   NY   6000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
       Name City
0      hema   NY
1  shivaram   LA
2   sravani   SF
3    harsha   NY
4    swathi   LA
5    sowmya   SF
6      maha   NY
7    killer   LA
8    sweety   SF
9     jannu   NY

DataFrame without City column:
       Name  Age   Salary
0      hema   22  50000.

C:\Users\Hema\AppData\Local\Temp\ipykernel_13848\2266953880.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(value=df2, inplace=True)
